# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import content_pb2 as content__pb2


class ContentManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateContent = channel.unary_unary(
                '/content.ContentManagement/CreateContent',
                request_serializer=content__pb2.NewContent.SerializeToString,
                response_deserializer=content__pb2.Content.FromString,
                )


class ContentManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateContent': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateContent,
                    request_deserializer=content__pb2.NewContent.FromString,
                    response_serializer=content__pb2.Content.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'content.ContentManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ContentManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/content.ContentManagement/CreateContent',
            content__pb2.NewContent.SerializeToString,
            content__pb2.Content.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
