# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: content.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcontent.proto\x12\x07\x63ontent\"\x1a\n\nNewContent\x12\x0c\n\x04text\x18\x01 \x01(\t\"#\n\x07\x43ontent\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04text\x18\x02 \x01(\t2K\n\x11\x43ontentManagement\x12\x36\n\rCreateContent\x12\x13.content.NewContent\x1a\x10.content.ContentB Z\x1egithub.com/rizafahmi/grpc-demob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'content_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\036github.com/rizafahmi/grpc-demo'
  _NEWCONTENT._serialized_start=26
  _NEWCONTENT._serialized_end=52
  _CONTENT._serialized_start=54
  _CONTENT._serialized_end=89
  _CONTENTMANAGEMENT._serialized_start=91
  _CONTENTMANAGEMENT._serialized_end=166
# @@protoc_insertion_point(module_scope)
